export type Oklch = readonly [number, number, number];

export const COLOR_NAMES = [
  "black",
  "blue",
  "violet",
  "orange",
  "red",
  "green",
  "yellow",
  "sky",
] as const;

export type Color = (typeof COLOR_NAMES)[number];

export const COLORS = {
  light: {
    black: [0, 0, 0],
    blue: [0.6204, 0.195, 253.83],
    violet: [0.7217, 0.1768, 305.49],
    orange: [0.6958, 0.2042, 43.48],
    red: [0.5814, 0.2348, 27.98],
    green: [0.7697, 0.2123, 148.69],
    yellow: [0.8606, 0.1731, 91.94],
    sky: [0.8276, 0.1013, 230.34],
  },
  dark: {
    black: [1, 0, 0],
    blue: [0.6204, 0.195, 253.83],
    violet: [0.7217, 0.1768, 305.49],
    orange: [0.6958, 0.2042, 43.48],
    red: [0.5814, 0.2348, 27.98],
    green: [0.7697, 0.2123, 148.69],
    yellow: [0.8606, 0.1731, 91.94],
    sky: [0.8276, 0.1013, 230.34],
  },
} satisfies Record<"light" | "dark", Record<Color, Oklch>>;

const GRADIENT_MODIFIERS = {
  start: { dl: 0.509, dc: -0.006, dh: -17.26 },
  end: { dl: -0.2326, dc: 0.1136, dh: 28.01 },
} as const;

export const toOklch = ([l, c, h]: Oklch) =>
  `oklch(${l.toFixed(4)} ${c.toFixed(4)} ${h.toFixed(2)})`;

const modifyColor = (
  [l, c, h]: Oklch,
  { dl = 0, dc = 0, dh = 0 }: { dl?: number; dc?: number; dh?: number },
): Oklch => [
  Math.min(1, Math.max(0, l + dl)),
  Math.max(0, c + dc),
  (h + dh + 360) % 360,
];

export const toColorGradient = (value: Oklch) =>
  `linear-gradient(in oklch 135deg, ${toOklch(modifyColor(value, GRADIENT_MODIFIERS.start))} 0%, ${toOklch(value)} 50%, ${toOklch(modifyColor(value, GRADIENT_MODIFIERS.end))} 100%)`;

export const colorVar = (color: Color) => `var(--loader-${color})`;

export const colorGradientVar = (color: Color) =>
  `var(--loader-${color}-gradient)`;

export function generateColorsCss() {
  const lines = [
    "/* This file is autogenerated by scripts/build-colors.mts */",
    "/* Do not edit this file directly. */",
    "",
  ];

  for (const [theme, colors] of Object.entries(COLORS) as Array<
    [keyof typeof COLORS, (typeof COLORS)[keyof typeof COLORS]]
  >) {
    const selector = theme === "light" ? ":root" : ".dark";
    lines.push(`${selector} {`);

    for (const color of COLOR_NAMES) {
      const value = colors[color];
      lines.push(`  --loader-${color}: ${toOklch(value)};`);
      lines.push(`  --loader-${color}-gradient: ${toColorGradient(value)};`);
    }

    lines.push("}", "");
  }

  return `${lines.join("\n")}\n`;
}
