// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  ring: {
    name: "ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  spokes: {
    name: "spokes",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/spokes.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/spokes.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  classic: {
    name: "classic",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/classic.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/classic.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dots-ring": {
    name: "dots-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/dots-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/dots-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  spiral: {
    name: "spiral",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/spiral.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/spiral.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  swirling: {
    name: "swirling",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/swirling.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/swirling.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  arc: {
    name: "arc",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/arc.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/arc.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dual-arc": {
    name: "dual-arc",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/dual-arc.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/dual-arc.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "concentric-ring": {
    name: "concentric-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/concentric-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/concentric-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "orbit-ring": {
    name: "orbit-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/orbit-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/orbit-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "satellite-ring": {
    name: "satellite-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/satellite-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/satellite-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "clock-ring": {
    name: "clock-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/clock-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/clock-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "quarter-ring": {
    name: "quarter-ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/quarter-ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/quarter-ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "comet-spinner": {
    name: "comet-spinner",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/comet-spinner.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/comet-spinner.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  pulse: {
    name: "pulse",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/pulse.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/pulse.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  ripple: {
    name: "ripple",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/ripple.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/ripple.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "pulse-dot": {
    name: "pulse-dot",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/pulse-dot.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/pulse-dot.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  dots: {
    name: "dots",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/dots.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/dots.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "bobbing-dots": {
    name: "bobbing-dots",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/bobbing-dots.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/bobbing-dots.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "bouncing-dots": {
    name: "bouncing-dots",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/bouncing-dots.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/bouncing-dots.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  typing: {
    name: "typing",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/typing.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/typing.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "twin-orbit": {
    name: "twin-orbit",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/twin-orbit.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/twin-orbit.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "pulsating-dots": {
    name: "pulsating-dots",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/pulsating-dots.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/pulsating-dots.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "triple-dot-spinner": {
    name: "triple-dot-spinner",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/triple-dot-spinner.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/triple-dot-spinner.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-shimmer": {
    name: "text-shimmer",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-shimmer.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-shimmer.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-blink": {
    name: "text-blink",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-blink.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-blink.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-dots": {
    name: "text-dots",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-dots.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-dots.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-shimmer-wave": {
    name: "text-shimmer-wave",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-shimmer-wave.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-shimmer-wave.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  wave: {
    name: "wave",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/wave.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/wave.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  bars: {
    name: "bars",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/bars.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/bars.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "analyzing-image": {
    name: "analyzing-image",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/analyzing-image.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/analyzing-image.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  skeleton: {
    name: "skeleton",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/skeleton.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/skeleton.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  terminal: {
    name: "terminal",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/terminal.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/terminal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  infinity: {
    name: "infinity",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/infinity.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/infinity.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "wandering-eyes": {
    name: "wandering-eyes",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/wandering-eyes.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/wandering-eyes.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "delivery-truck": {
    name: "delivery-truck",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/delivery-truck.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/delivery-truck.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "polar-face": {
    name: "polar-face",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/polar-face.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/polar-face.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/utils.ts",
        type: "registry:lib",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
