// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  ring: {
    name: "ring",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/ring.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/ring.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  spokes: {
    name: "spokes",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/spokes.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/spokes.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  classic: {
    name: "classic",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/classic.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/classic.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "analyzing-image": {
    name: "analyzing-image",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/analyzing-image.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/analyzing-image.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  skeleton: {
    name: "skeleton",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/skeleton.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/skeleton.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  swirling: {
    name: "swirling",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/swirling.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/swirling.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  arc: {
    name: "arc",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/arc.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/arc.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dual-arc": {
    name: "dual-arc",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/dual-arc.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/loading-ui/dual-arc.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-shimmer": {
    name: "text-shimmer",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-shimmer.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-shimmer.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-shimmer-wave": {
    name: "text-shimmer-wave",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/components/loading-ui/text-shimmer-wave.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod =
        await import("@/registry/components/loading-ui/text-shimmer-wave.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/utils.ts",
        type: "registry:lib",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
