name: Setup
description: Composite action that sets up bun and installs dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v7
      with:
        node-version: 22.x

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install --frozen-lockfile
      shell: bash
