import { registry } from "../registry";
import path from "node:path";
import fs from "node:fs/promises";
import { exec } from "node:child_process";
import { format } from "oxfmt";
import { RegistryItem } from "shadcn/schema";

function normalizeRegistryFiles(item: RegistryItem): Array<{
  path: string;
  type: string;
  target?: string;
}> {
  return (
    item.files?.map((file) => ({
      path: typeof file === "string" ? file : file.path,
      type: typeof file === "string" ? item.type : file.type,
      target: typeof file === "string" ? undefined : file.target,
    })) ?? []
  );
}

async function readFileIfExists(filePath: string) {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }

    throw error;
  }
}

async function writeIfChanged(filePath: string, content: string) {
  const existingContent = await readFileIfExists(filePath);
  if (existingContent === content) {
    return false;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);

  return true;
}

async function formatGeneratedSource(content: string, filePath: string) {
  const config = JSON.parse(
    await fs.readFile(path.join(process.cwd(), ".oxfmtrc.json"), "utf8"),
  );
  return (await format(filePath, content, config)).code;
}

async function formatGeneratedJson(value: unknown, filePath: string) {
  return formatGeneratedSource(JSON.stringify(value, null, 2), filePath);
}

async function buildExamplesIndex() {
  const examplesDir = path.join(process.cwd(), "registry/examples");

  const allEntries = await fs.readdir(examplesDir, { withFileTypes: true });
  const files = allEntries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith(".tsx") &&
        !entry.name.startsWith("__"),
    )
    .map((entry) => entry.name)
    .sort();

  console.log(`   Found ${files.length} demos for examples`);

  let index = `// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react"

export const ExamplesIndex: Record<string, Record<string, any>> = {`;

  for (const file of files) {
    const name = file.replace(/\.tsx$/, "");

    index += `
    "${name}": {
      name: "${name}",
      filePath: "registry/examples/${file}",
      component: React.lazy(async () => {
        const mod = await import("./${file}")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${name}"
        return { default: mod.default || mod[exportName] }
      }),
    },`;
  }

  index += `
  };`;

  const outputPath = path.join(examplesDir, "__index__.tsx");
  await writeIfChanged(
    outputPath,
    await formatGeneratedSource(index, outputPath),
  );
}

async function buildRegistryIndex() {
  let index = `// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const files = normalizeRegistryFiles(item);

    if (!files.length) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${item.files[0].path}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${
      item.files
        ?.map((file) => {
          const filePath = `registry/${typeof file === "string" ? file : file.path}`;
          const resolvedFilePath = path.resolve(filePath);
          return typeof file === "string"
            ? `"${resolvedFilePath}"`
            : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
        })
        .join(",\n") ?? ""
    }],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  const outputPath = path.join(process.cwd(), "registry/__index__.tsx");
  await writeIfChanged(
    outputPath,
    await formatGeneratedSource(index, outputPath),
  );
}

async function buildRegistryJsonFile() {
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = normalizeRegistryFiles(item).map((file) =>
        Object.assign({}, file, {
          path: `registry/${file.path}`,
          target: file.target ?? "",
        }),
      );
      return files.length > 0 ? Object.assign({}, item, { files }) : item;
    }),
  };

  const registryJsonPath = path.join(process.cwd(), "registry.json");
  const registryJson = await formatGeneratedJson(
    fixedRegistry,
    registryJsonPath,
  );
  await writeIfChanged(registryJsonPath, registryJson);
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    exec(
      `shadcn build registry.json --output public/r`,
      async (error, stdout, stderr) => {
        if (error) {
          if (stderr) {
            console.error(stderr);
          } else {
            console.error(`Error: ${error.message}`);
          }
          reject(error);
          return;
        }
        if (stdout) {
          console.log(stdout);
        }
        if (stderr) {
          console.log(stderr);
        }

        resolve(undefined);
      },
    );
  });
}

try {
  const totalStart = performance.now();

  console.log("🗂️ Building registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("\n📋 Building registry/examples/__index__.tsx...");
  await buildExamplesIndex();

  console.log("💅 Building registry.json...");
  await buildRegistryJsonFile();

  console.log("🏗️ Building registry...");
  await buildRegistry();

  const elapsed = ((performance.now() - totalStart) / 1000).toFixed(2);
  console.log(`\n✅ Build complete in ${elapsed}s!`);
} catch (error) {
  console.error(error);
  process.exit(1);
}
