// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react";

export const ExamplesIndex: Record<string, Record<string, any>> = {
  "analyzing-image-demo": {
    name: "analyzing-image-demo",
    filePath: "registry/examples/analyzing-image/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./analyzing-image/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "analyzing-image-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "arc-demo": {
    name: "arc-demo",
    filePath: "registry/examples/arc/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./arc/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "arc-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bars-demo": {
    name: "bars-demo",
    filePath: "registry/examples/bars/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./bars/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "bars-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bobbing-dots-demo": {
    name: "bobbing-dots-demo",
    filePath: "registry/examples/bobbing-dots/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./bobbing-dots/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "bobbing-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bouncing-dots-demo": {
    name: "bouncing-dots-demo",
    filePath: "registry/examples/bouncing-dots/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./bouncing-dots/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "bouncing-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "classic-demo": {
    name: "classic-demo",
    filePath: "registry/examples/classic/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./classic/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "classic-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "clock-ring-demo": {
    name: "clock-ring-demo",
    filePath: "registry/examples/clock-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./clock-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "clock-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "comet-spinner-demo": {
    name: "comet-spinner-demo",
    filePath: "registry/examples/comet-spinner/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./comet-spinner/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "comet-spinner-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "concentric-ring-demo": {
    name: "concentric-ring-demo",
    filePath: "registry/examples/concentric-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./concentric-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "concentric-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dash-ring-demo": {
    name: "dash-ring-demo",
    filePath: "registry/examples/dash-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dash-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dash-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dots-ring-demo": {
    name: "dots-ring-demo",
    filePath: "registry/examples/dots-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dots-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dots-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dots-demo": {
    name: "dots-demo",
    filePath: "registry/examples/dots/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dots/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dual-arc-demo": {
    name: "dual-arc-demo",
    filePath: "registry/examples/dual-arc/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dual-arc/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dual-arc-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "infinity-demo": {
    name: "infinity-demo",
    filePath: "registry/examples/infinity/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./infinity/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "infinity-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "orbit-ring-demo": {
    name: "orbit-ring-demo",
    filePath: "registry/examples/orbit-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./orbit-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "orbit-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "pulsating-dots-demo": {
    name: "pulsating-dots-demo",
    filePath: "registry/examples/pulsating-dots/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./pulsating-dots/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "pulsating-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "pulse-dot-demo": {
    name: "pulse-dot-demo",
    filePath: "registry/examples/pulse-dot/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./pulse-dot/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "pulse-dot-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "pulse-demo": {
    name: "pulse-demo",
    filePath: "registry/examples/pulse/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./pulse/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "pulse-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "quarter-ring-demo": {
    name: "quarter-ring-demo",
    filePath: "registry/examples/quarter-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./quarter-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "quarter-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-badge": {
    name: "ring-badge",
    filePath: "registry/examples/ring/badge.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/badge.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-badge";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-button": {
    name: "ring-button",
    filePath: "registry/examples/ring/button.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-button";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-color": {
    name: "ring-color",
    filePath: "registry/examples/ring/color.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/color.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-color";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-demo": {
    name: "ring-demo",
    filePath: "registry/examples/ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-direction": {
    name: "ring-direction",
    filePath: "registry/examples/ring/direction.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/direction.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-direction";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-duration": {
    name: "ring-duration",
    filePath: "registry/examples/ring/duration.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/duration.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-duration";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-empty": {
    name: "ring-empty",
    filePath: "registry/examples/ring/empty.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/empty.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-empty";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-input-group": {
    name: "ring-input-group",
    filePath: "registry/examples/ring/input-group.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/input-group.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-input-group";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-size": {
    name: "ring-size",
    filePath: "registry/examples/ring/size.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring/size.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-size";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ripple-demo": {
    name: "ripple-demo",
    filePath: "registry/examples/ripple/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ripple/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ripple-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "satellite-ring-demo": {
    name: "satellite-ring-demo",
    filePath: "registry/examples/satellite-ring/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./satellite-ring/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "satellite-ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "skeleton-demo": {
    name: "skeleton-demo",
    filePath: "registry/examples/skeleton/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./skeleton/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "skeleton-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spiral-demo": {
    name: "spiral-demo",
    filePath: "registry/examples/spiral/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spiral/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spiral-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-alert": {
    name: "spokes-alert",
    filePath: "registry/examples/spokes/alert.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/alert.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-alert";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-badge": {
    name: "spokes-badge",
    filePath: "registry/examples/spokes/badge.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/badge.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-badge";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-button": {
    name: "spokes-button",
    filePath: "registry/examples/spokes/button.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-button";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-color": {
    name: "spokes-color",
    filePath: "registry/examples/spokes/color.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/color.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-color";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-demo": {
    name: "spokes-demo",
    filePath: "registry/examples/spokes/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-duration": {
    name: "spokes-duration",
    filePath: "registry/examples/spokes/duration.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/duration.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-duration";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-input-group": {
    name: "spokes-input-group",
    filePath: "registry/examples/spokes/input-group.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/input-group.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-input-group";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-size": {
    name: "spokes-size",
    filePath: "registry/examples/spokes/size.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/size.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-size";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-stroke-width": {
    name: "spokes-stroke-width",
    filePath: "registry/examples/spokes/stroke-width.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes/stroke-width.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-stroke-width";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "swirling-demo": {
    name: "swirling-demo",
    filePath: "registry/examples/swirling/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./swirling/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "swirling-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "terminal-demo": {
    name: "terminal-demo",
    filePath: "registry/examples/terminal/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./terminal/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "terminal-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-blink-demo": {
    name: "text-blink-demo",
    filePath: "registry/examples/text-blink/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-blink/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-blink-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-dots-demo": {
    name: "text-dots-demo",
    filePath: "registry/examples/text-dots/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-dots/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-shimmer-wave-demo": {
    name: "text-shimmer-wave-demo",
    filePath: "registry/examples/text-shimmer-wave/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-shimmer-wave/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-shimmer-wave-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-shimmer-demo": {
    name: "text-shimmer-demo",
    filePath: "registry/examples/text-shimmer/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-shimmer/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-shimmer-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "triple-dot-spinner-demo": {
    name: "triple-dot-spinner-demo",
    filePath: "registry/examples/triple-dot-spinner/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./triple-dot-spinner/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "triple-dot-spinner-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "twin-orbit-demo": {
    name: "twin-orbit-demo",
    filePath: "registry/examples/twin-orbit/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./twin-orbit/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "twin-orbit-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "typing-demo": {
    name: "typing-demo",
    filePath: "registry/examples/typing/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./typing/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "typing-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "wandering-eyes-demo": {
    name: "wandering-eyes-demo",
    filePath: "registry/examples/wandering-eyes/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./wandering-eyes/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "wandering-eyes-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "wave-demo": {
    name: "wave-demo",
    filePath: "registry/examples/wave/demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./wave/demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "wave-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
};
