/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as llmsLlmsFullDottxtRouteImport } from './routes/(llms)/llms-full[.]txt'
import { Route as llmsLlmsDottxtRouteImport } from './routes/(llms)/llms[.]txt'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeSponsorsRouteImport } from './routes/_home/sponsors'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as IngestSplatRouteImport } from './routes/ingest/$'
import { Route as ApiOgSplatRouteImport } from './routes/api/og/$'
import { Route as llmsLlmsDotmdxDocsSplatRouteImport } from './routes/(llms)/llms[.]mdx.docs.$'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const llmsLlmsFullDottxtRoute = llmsLlmsFullDottxtRouteImport.update({
  id: '/(llms)/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const llmsLlmsDottxtRoute = llmsLlmsDottxtRouteImport.update({
  id: '/(llms)/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSponsorsRoute = HomeSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => HomeRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSplatRoute = ApiOgSplatRouteImport.update({
  id: '/api/og/$',
  path: '/api/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const llmsLlmsDotmdxDocsSplatRoute = llmsLlmsDotmdxDocsSplatRouteImport.update({
  id: '/(llms)/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/llms.txt': typeof llmsLlmsDottxtRoute
  '/sponsors': typeof HomeSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/llms.mdx/docs/$': typeof llmsLlmsDotmdxDocsSplatRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/llms.txt': typeof llmsLlmsDottxtRoute
  '/sponsors': typeof HomeSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/': typeof HomeIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/llms.mdx/docs/$': typeof llmsLlmsDotmdxDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(llms)/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/(llms)/llms.txt': typeof llmsLlmsDottxtRoute
  '/_home/sponsors': typeof HomeSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/ingest/$': typeof IngestSplatRoute
  '/_home/': typeof HomeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/(llms)/llms.mdx/docs/$': typeof llmsLlmsDotmdxDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/ingest/$'
    | '/docs/'
    | '/api/og/$'
    | '/llms.mdx/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/ingest/$'
    | '/'
    | '/docs'
    | '/api/og/$'
    | '/llms.mdx/docs/$'
  id:
    | '__root__'
    | '/_home'
    | '/docs'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(llms)/llms-full.txt'
    | '/(llms)/llms.txt'
    | '/_home/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/ingest/$'
    | '/_home/'
    | '/docs/'
    | '/api/og/$'
    | '/(llms)/llms.mdx/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  llmsLlmsFullDottxtRoute: typeof llmsLlmsFullDottxtRoute
  llmsLlmsDottxtRoute: typeof llmsLlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  IngestSplatRoute: typeof IngestSplatRoute
  ApiOgSplatRoute: typeof ApiOgSplatRoute
  llmsLlmsDotmdxDocsSplatRoute: typeof llmsLlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(llms)/llms-full.txt': {
      id: '/(llms)/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof llmsLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(llms)/llms.txt': {
      id: '/(llms)/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof llmsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/sponsors': {
      id: '/_home/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof HomeSponsorsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$': {
      id: '/api/og/$'
      path: '/api/og/$'
      fullPath: '/api/og/$'
      preLoaderRoute: typeof ApiOgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(llms)/llms.mdx/docs/$': {
      id: '/(llms)/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof llmsLlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteRouteChildren {
  HomeSponsorsRoute: typeof HomeSponsorsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeSponsorsRoute: HomeSponsorsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  llmsLlmsFullDottxtRoute: llmsLlmsFullDottxtRoute,
  llmsLlmsDottxtRoute: llmsLlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  IngestSplatRoute: IngestSplatRoute,
  ApiOgSplatRoute: ApiOgSplatRoute,
  llmsLlmsDotmdxDocsSplatRoute: llmsLlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
